// lib/catalog.ts
import type { Test } from './schema';

export interface CatalogEntry {
  slug: string;
  title: string;
  category: Test['category'];
  theme: string;
  mode: Test['mode'];
  status: 'live' | 'backlog';
  hasCover: boolean;
  virality: number | null;
}

export interface CatalogInputs {
  tests: Test[];
  published: Set<string>;
  covers: Set<string>;            // slugs (no extension) that have a cover
  virality: Map<string, number>;  // slug -> score
}

export function buildCatalog(inp: CatalogInputs): CatalogEntry[] {
  return inp.tests
    .map((t): CatalogEntry => ({
      slug: t.slug,
      title: t.title,
      category: t.category,
      theme: t.theme ?? 'unclassified',
      mode: t.mode,
      status: inp.published.has(t.slug) ? 'live' : 'backlog',
      hasCover: inp.covers.has(t.slug),
      virality: inp.virality.get(t.slug) ?? null,
    }))
    .sort((a, b) =>
      a.category.localeCompare(b.category) ||
      a.theme.localeCompare(b.theme) ||
      (b.virality ?? 0) - (a.virality ?? 0) ||
      a.title.localeCompare(b.title));
}

function groupBy<T>(items: T[], key: (i: T) => string): Map<string, T[]> {
  const m = new Map<string, T[]>();
  for (const i of items) {
    const k = key(i);
    const arr = m.get(k);
    if (arr) arr.push(i); else m.set(k, [i]);
  }
  return m;
}

export function renderCatalogMarkdown(entries: CatalogEntry[]): string {
  const live = entries.filter(e => e.status === 'live').length;
  const cover = entries.filter(e => e.hasCover).length;
  const out: string[] = [];
  out.push('# Parable quiz catalog', '');
  out.push('_Generated by `pnpm build:catalog`. Do not edit by hand._', '');
  out.push(`**${entries.length}** quizzes · **${live}** live · **${entries.length - live}** backlog · **${cover}** with cover art`, '');

  for (const [cat, catEntries] of [...groupBy(entries, e => e.category)].sort()) {
    out.push(`## ${cat} (${catEntries.length})`, '');
    for (const [theme, themeEntries] of [...groupBy(catEntries, e => e.theme)].sort()) {
      out.push(`### ${theme} (${themeEntries.length})`, '');
      out.push('| Title | Slug | Status | Cover | Virality |', '| --- | --- | --- | --- | --- |');
      for (const e of themeEntries) {
        out.push(`| ${e.title} | \`${e.slug}\` | ${e.status === 'live' ? '**LIVE**' : 'backlog'} | ${e.hasCover ? '✓' : '–'} | ${e.virality ?? '–'} |`);
      }
      out.push('');
    }
  }
  return out.join('\n') + '\n';
}
