// lib/reward-catalog.ts
import type { Test } from './schema';

export interface RewardEntry {
  quizSlug: string;
  quizTitle: string;
  resultKey: string;
  resultName: string;
  rewardArt: string;
  category: Test['category'];
  status: 'live' | 'backlog';
  hasImage: boolean;
  path: string; // public/results/<slug>/<key>.png
}

export interface RewardCatalogInputs {
  tests: Test[];
  published: Set<string>;
  hasImage: (slug: string, key: string) => boolean;
}

export function buildRewardCatalog(inp: RewardCatalogInputs): RewardEntry[] {
  const out: RewardEntry[] = [];
  for (const t of inp.tests) {
    if (t.mode === 'knowledge') {
      // Score-based: one quiz-level scene image at <slug>/card, shown for any score.
      out.push({
        quizSlug: t.slug,
        quizTitle: t.title,
        resultKey: 'card',
        resultName: 'Score card',
        rewardArt: 'scene',
        category: t.category,
        status: inp.published.has(t.slug) ? 'live' : 'backlog',
        hasImage: inp.hasImage(t.slug, 'card'),
        path: `public/results/${t.slug}/card.png`,
      });
      continue;
    }
    for (const [key, r] of Object.entries(t.results)) {
      out.push({
        quizSlug: t.slug,
        quizTitle: t.title,
        resultKey: key,
        resultName: (r as { name: string }).name,
        rewardArt: (r as { rewardArt?: string }).rewardArt ?? 'untagged',
        category: t.category,
        status: inp.published.has(t.slug) ? 'live' : 'backlog',
        hasImage: inp.hasImage(t.slug, key),
        path: `public/results/${t.slug}/${key}.png`,
      });
    }
  }
  return out.sort((a, b) =>
    a.rewardArt.localeCompare(b.rewardArt) ||
    a.quizSlug.localeCompare(b.quizSlug) ||
    a.resultKey.localeCompare(b.resultKey));
}

function groupBy<T>(items: T[], key: (i: T) => string): Map<string, T[]> {
  const m = new Map<string, T[]>();
  for (const i of items) { const k = key(i); const a = m.get(k); if (a) a.push(i); else m.set(k, [i]); }
  return m;
}

export function renderRewardCatalogMarkdown(entries: RewardEntry[]): string {
  const live = entries.filter(e => e.status === 'live');
  const withImg = entries.filter(e => e.hasImage).length;
  const out: string[] = [];
  out.push('# Reward-card repertory', '');
  out.push('_Generated by `pnpm build:reward-catalog`. Do not edit by hand._', '');
  out.push(`**${entries.length}** reward images · **${live.length}** live · **${withImg}** generated · **${live.length - live.filter(e => e.hasImage).length}** live still missing art`, '');
  for (const [type, group] of [...groupBy(entries, e => e.rewardArt)].sort()) {
    out.push(`## ${type} (${group.length})`, '');
    for (const [slug, rows] of [...groupBy(group, e => e.quizSlug)].sort()) {
      out.push(`### ${rows[0].quizTitle} \`${slug}\``, '');
      out.push('| Result | Path | Status | Image |', '| --- | --- | --- | --- |');
      for (const e of rows) {
        out.push(`| ${e.resultName} | \`${e.path}\` | ${e.status === 'live' ? '**LIVE**' : 'backlog'} | ${e.hasImage ? '✓' : '–'} |`);
      }
      out.push('');
    }
  }
  return out.join('\n') + '\n';
}
